# @package _global_
optimizer_id: CARPSDynamicRF
optimizer_container_id: CARPSDynamicRF
optimizer:
  _target_: carps_integration.optimizer.CARPSDynamicRFOptimizer
  _partial_: true
  extractor_name: standard_disagreement
  n_init: 10
  kappa: 1.96
  telemetry_path: "dyrf_bo_telemetry.json"
  window_size: 5
  min_samples_leaf_base: 2
  min_samples_leaf_min: 1
  min_samples_leaf_max: 15
  alpha: 1.0
  max_features_base: 0.5
  max_features_min: 0.1
  max_features_max: 0.8
  eta: 0.5
