# @package _global_
optimizer_id: CARPSDynamicRF
optimizer_container_id: CARPSDynamicRF
optimizer:
  _target_: carps_integration.optimizer.CARPSDynamicRFOptimizer
  _partial_: true
  extractor_name: standard_disagreement
  n_init: 10
  kappa: 1.96
  telemetry_path: "dyrf_bo_telemetry.json"
  window_size: 5
  n_base: 100
  n_min: 10
  n_max: 200
  gamma: 1.0
  depth_base: 12
  depth_min: 5
  depth_max: 30
  beta: 5.0
