# @package _global_
defaults:
  - /optimizer/smac20/base
optimizer_id: SMAC20_ProximityLCB_k10
optimizer_container_id: SMAC20_ProximityLCB
optimizer:
  acq_func_name: "proximity_lcb"
  acq_func_kwargs:
    k: 10
    level: 0.95
    eps: 0.10
    k_warmup: 10
  smac_cfg:
    smac_class: smac.facade.HyperparameterOptimizationFacade
    model_class: carps_integration.custom_uncertainty_model.CustomUncertaintyRandomForest
    model_kwargs:
      uncertainty_func: "proximity_b"
      extractor_kwargs:
        decay_lambda: 1.0
