# @package _global_
defaults:
  - /optimizer/smac20/base
optimizer_id: SMAC20_CustomUncertainty
optimizer_container_id: SMAC20_CustomUncertainty
optimizer:
  smac_cfg:
    smac_class: smac.facade.HyperparameterOptimizationFacade
    model_class: carps_integration.custom_uncertainty_model.CustomUncertaintyRandomForest
    model_kwargs:
      uncertainty_func: "proximity_bc"
